
### get lista
 GET http://localhost:8080/signup HTTP/1.1

### post post 
 POST http://localhost:8080/post HTTP/1.1s
 Content-Type: application/json

 {
    "id": "testoxxssxs"
 }

### get posts
 GET http://localhost:8080/post HTTP/1.1