@port = {{$dotenv PORT}}

### HEALTH
GET http://localhost:{{port}}/health HTTP/1.1

### SIGNUP
POST http://localhost:{{port}}/auth/signup HTTP/1.1
Content-Type: application/json

{
   "username": "xd lordaso",
   "email": "xD@aaaaxd.xd",
   "password": "aoisjfhoaisjfoias"
}


