### HEALTH
GET http://localhost:8080/health HTTP/1.1

### SIGNUP
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
   "username": "",
   "email": "",
   "password": "aoisjfhoaisjfoias"
}
